// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simRegistration.proto

/*
Package simRegistration is a generated protocol buffer package.

It is generated from these files:
	simRegistration.proto

It has these top-level messages:
	CustomerDetails
	CreateResponseMessage
*/
package simRegistration

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CustomerDetails struct {
	CustId                 int32                       `protobuf:"varint,1,opt,name=custId" json:"custId,omitempty"`
	CustName               string                      `protobuf:"bytes,2,opt,name=custName" json:"custName,omitempty"`
	Email                  string                      `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	AlternateContactNumber string                      `protobuf:"bytes,4,opt,name=alternateContactNumber" json:"alternateContactNumber,omitempty"`
	AadharNumber           int64                       `protobuf:"varint,5,opt,name=aadharNumber" json:"aadharNumber,omitempty"`
	Addresses              []*CustomerDetails_Addrress `protobuf:"bytes,6,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *CustomerDetails) Reset()                    { *m = CustomerDetails{} }
func (m *CustomerDetails) String() string            { return proto.CompactTextString(m) }
func (*CustomerDetails) ProtoMessage()               {}
func (*CustomerDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CustomerDetails) GetCustId() int32 {
	if m != nil {
		return m.CustId
	}
	return 0
}

func (m *CustomerDetails) GetCustName() string {
	if m != nil {
		return m.CustName
	}
	return ""
}

func (m *CustomerDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerDetails) GetAlternateContactNumber() string {
	if m != nil {
		return m.AlternateContactNumber
	}
	return ""
}

func (m *CustomerDetails) GetAadharNumber() int64 {
	if m != nil {
		return m.AadharNumber
	}
	return 0
}

func (m *CustomerDetails) GetAddresses() []*CustomerDetails_Addrress {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CustomerDetails_Addrress struct {
	HouseNumber string `protobuf:"bytes,1,opt,name=houseNumber" json:"houseNumber,omitempty"`
	Street      string `protobuf:"bytes,2,opt,name=street" json:"street,omitempty"`
	City        string `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	State       string `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	Zip         int32  `protobuf:"varint,5,opt,name=zip" json:"zip,omitempty"`
}

func (m *CustomerDetails_Addrress) Reset()                    { *m = CustomerDetails_Addrress{} }
func (m *CustomerDetails_Addrress) String() string            { return proto.CompactTextString(m) }
func (*CustomerDetails_Addrress) ProtoMessage()               {}
func (*CustomerDetails_Addrress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *CustomerDetails_Addrress) GetHouseNumber() string {
	if m != nil {
		return m.HouseNumber
	}
	return ""
}

func (m *CustomerDetails_Addrress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CustomerDetails_Addrress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CustomerDetails_Addrress) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CustomerDetails_Addrress) GetZip() int32 {
	if m != nil {
		return m.Zip
	}
	return 0
}

type CreateResponseMessage struct {
	CustId     int32  `protobuf:"varint,1,opt,name=custId" json:"custId,omitempty"`
	SuccessMsg string `protobuf:"bytes,2,opt,name=successMsg" json:"successMsg,omitempty"`
}

func (m *CreateResponseMessage) Reset()                    { *m = CreateResponseMessage{} }
func (m *CreateResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*CreateResponseMessage) ProtoMessage()               {}
func (*CreateResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateResponseMessage) GetCustId() int32 {
	if m != nil {
		return m.CustId
	}
	return 0
}

func (m *CreateResponseMessage) GetSuccessMsg() string {
	if m != nil {
		return m.SuccessMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomerDetails)(nil), "simRegistration.CustomerDetails")
	proto.RegisterType((*CustomerDetails_Addrress)(nil), "simRegistration.CustomerDetails.Addrress")
	proto.RegisterType((*CreateResponseMessage)(nil), "simRegistration.CreateResponseMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SimRegistration service

type SimRegistrationClient interface {
	RegisterCustomer(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*CreateResponseMessage, error)
}

type simRegistrationClient struct {
	cc *grpc.ClientConn
}

func NewSimRegistrationClient(cc *grpc.ClientConn) SimRegistrationClient {
	return &simRegistrationClient{cc}
}

func (c *simRegistrationClient) RegisterCustomer(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*CreateResponseMessage, error) {
	out := new(CreateResponseMessage)
	err := grpc.Invoke(ctx, "/simRegistration.SimRegistration/RegisterCustomer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SimRegistration service

type SimRegistrationServer interface {
	RegisterCustomer(context.Context, *CustomerDetails) (*CreateResponseMessage, error)
}

func RegisterSimRegistrationServer(s *grpc.Server, srv SimRegistrationServer) {
	s.RegisterService(&_SimRegistration_serviceDesc, srv)
}

func _SimRegistration_RegisterCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimRegistrationServer).RegisterCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simRegistration.SimRegistration/RegisterCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimRegistrationServer).RegisterCustomer(ctx, req.(*CustomerDetails))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimRegistration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simRegistration.SimRegistration",
	HandlerType: (*SimRegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCustomer",
			Handler:    _SimRegistration_RegisterCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simRegistration.proto",
}

func init() { proto.RegisterFile("simRegistration.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6b, 0xe2, 0x50,
	0x10, 0xc6, 0x37, 0x1b, 0x23, 0x3a, 0x2e, 0x28, 0x8f, 0x55, 0x82, 0x87, 0x25, 0xe4, 0xb0, 0xa4,
	0x17, 0x0f, 0x16, 0x7a, 0x2f, 0x16, 0x4a, 0x0f, 0x5a, 0x48, 0xef, 0x85, 0x31, 0x19, 0xf4, 0x81,
	0xc9, 0xb3, 0x6f, 0x26, 0x87, 0xf6, 0x54, 0xe8, 0x3f, 0x5e, 0x12, 0x9f, 0xad, 0xda, 0x4a, 0x6f,
	0xf3, 0x7d, 0x33, 0x43, 0xe6, 0xfb, 0xe5, 0xc1, 0x90, 0x75, 0x91, 0xd2, 0x4a, 0xb3, 0x58, 0x14,
	0x6d, 0xca, 0xc9, 0xd6, 0x1a, 0x31, 0xaa, 0x7f, 0x62, 0xc7, 0x6f, 0x3e, 0xf4, 0x67, 0x15, 0x8b,
	0x29, 0xc8, 0xde, 0x90, 0xa0, 0xde, 0xb0, 0x1a, 0x41, 0x3b, 0xab, 0x58, 0xee, 0xf2, 0xd0, 0x8b,
	0xbc, 0x24, 0x48, 0x9d, 0x52, 0x63, 0xe8, 0xd4, 0xd5, 0x02, 0x0b, 0x0a, 0x7f, 0x47, 0x5e, 0xd2,
	0x4d, 0x3f, 0xb4, 0xfa, 0x0b, 0x01, 0x15, 0xa8, 0x37, 0xa1, 0xdf, 0x34, 0x76, 0x42, 0x5d, 0xc1,
	0x08, 0x37, 0x42, 0xb6, 0x44, 0xa1, 0x99, 0x29, 0x05, 0x33, 0x59, 0x54, 0xc5, 0x92, 0x6c, 0xd8,
	0x6a, 0xc6, 0xce, 0x74, 0x55, 0x0c, 0x7f, 0x10, 0xf3, 0x35, 0x5a, 0x37, 0x1d, 0x44, 0x5e, 0xe2,
	0xa7, 0x47, 0x9e, 0xba, 0x85, 0x2e, 0xe6, 0xb9, 0x25, 0x66, 0xe2, 0xb0, 0x1d, 0xf9, 0x49, 0x6f,
	0x7a, 0x31, 0x39, 0x4d, 0x7d, 0x12, 0x6d, 0x72, 0x9d, 0xe7, 0xb6, 0x5e, 0x49, 0x3f, 0x77, 0xc7,
	0xaf, 0x1e, 0x74, 0xf6, 0xbe, 0x8a, 0xa0, 0xb7, 0x36, 0x15, 0x93, 0xfb, 0xb0, 0xd7, 0x9c, 0x79,
	0x68, 0xd5, 0x74, 0x58, 0x2c, 0x91, 0x38, 0x06, 0x4e, 0x29, 0x05, 0xad, 0x4c, 0xcb, 0xb3, 0x03,
	0xd0, 0xd4, 0x35, 0x15, 0x16, 0x14, 0x72, 0x71, 0x77, 0x42, 0x0d, 0xc0, 0x7f, 0xd1, 0xdb, 0x26,
	0x54, 0x90, 0xd6, 0x65, 0x7c, 0x0f, 0xc3, 0x99, 0x25, 0x14, 0x4a, 0x89, 0xb7, 0xa6, 0x64, 0x9a,
	0x13, 0x33, 0xae, 0xe8, 0xec, 0xaf, 0xf8, 0x07, 0xc0, 0x55, 0x96, 0x11, 0xf3, 0x9c, 0x57, 0xee,
	0x90, 0x03, 0x67, 0xfa, 0x04, 0xfd, 0x87, 0x63, 0x14, 0xea, 0x11, 0x06, 0x3b, 0x4d, 0x76, 0x4f,
	0x45, 0x45, 0x3f, 0x01, 0x1b, 0xff, 0xff, 0x3a, 0xf1, 0xdd, 0xa1, 0xf1, 0xaf, 0x65, 0xbb, 0x79,
	0x61, 0x97, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x24, 0xcc, 0xd1, 0x7a, 0x02, 0x00, 0x00,
}
