// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkDuplicateCustomer.proto

/*
Package checkDuplicateCustomer is a generated protocol buffer package.

It is generated from these files:
	checkDuplicateCustomer.proto

It has these top-level messages:
	RequestMsg
	ResponseMsg
*/
package checkDuplicateCustomer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestMsg struct {
	AadharNumber int64 `protobuf:"varint,1,opt,name=aadharNumber" json:"aadharNumber,omitempty"`
}

func (m *RequestMsg) Reset()                    { *m = RequestMsg{} }
func (m *RequestMsg) String() string            { return proto.CompactTextString(m) }
func (*RequestMsg) ProtoMessage()               {}
func (*RequestMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestMsg) GetAadharNumber() int64 {
	if m != nil {
		return m.AadharNumber
	}
	return 0
}

type ResponseMsg struct {
	CustExist bool `protobuf:"varint,1,opt,name=custExist" json:"custExist,omitempty"`
}

func (m *ResponseMsg) Reset()                    { *m = ResponseMsg{} }
func (m *ResponseMsg) String() string            { return proto.CompactTextString(m) }
func (*ResponseMsg) ProtoMessage()               {}
func (*ResponseMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseMsg) GetCustExist() bool {
	if m != nil {
		return m.CustExist
	}
	return false
}

func init() {
	proto.RegisterType((*RequestMsg)(nil), "checkDuplicateCustomer.RequestMsg")
	proto.RegisterType((*ResponseMsg)(nil), "checkDuplicateCustomer.ResponseMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CheckDuplicateCustomer service

type CheckDuplicateCustomerClient interface {
	CheckDuplicateCustomerBeforeCreate(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ResponseMsg, error)
}

type checkDuplicateCustomerClient struct {
	cc *grpc.ClientConn
}

func NewCheckDuplicateCustomerClient(cc *grpc.ClientConn) CheckDuplicateCustomerClient {
	return &checkDuplicateCustomerClient{cc}
}

func (c *checkDuplicateCustomerClient) CheckDuplicateCustomerBeforeCreate(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ResponseMsg, error) {
	out := new(ResponseMsg)
	err := grpc.Invoke(ctx, "/checkDuplicateCustomer.CheckDuplicateCustomer/CheckDuplicateCustomerBeforeCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CheckDuplicateCustomer service

type CheckDuplicateCustomerServer interface {
	CheckDuplicateCustomerBeforeCreate(context.Context, *RequestMsg) (*ResponseMsg, error)
}

func RegisterCheckDuplicateCustomerServer(s *grpc.Server, srv CheckDuplicateCustomerServer) {
	s.RegisterService(&_CheckDuplicateCustomer_serviceDesc, srv)
}

func _CheckDuplicateCustomer_CheckDuplicateCustomerBeforeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckDuplicateCustomerServer).CheckDuplicateCustomerBeforeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/checkDuplicateCustomer.CheckDuplicateCustomer/CheckDuplicateCustomerBeforeCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckDuplicateCustomerServer).CheckDuplicateCustomerBeforeCreate(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckDuplicateCustomer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "checkDuplicateCustomer.CheckDuplicateCustomer",
	HandlerType: (*CheckDuplicateCustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDuplicateCustomerBeforeCreate",
			Handler:    _CheckDuplicateCustomer_CheckDuplicateCustomerBeforeCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkDuplicateCustomer.proto",
}

func init() { proto.RegisterFile("checkDuplicateCustomer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xce, 0x48, 0x4d,
	0xce, 0x76, 0x29, 0x2d, 0xc8, 0xc9, 0x4c, 0x4e, 0x2c, 0x49, 0x75, 0x2e, 0x2d, 0x2e, 0xc9, 0xcf,
	0x4d, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc3, 0x2e, 0xab, 0x64, 0xc0, 0xc5,
	0x15, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0xe2, 0x5b, 0x9c, 0x2e, 0xa4, 0xc4, 0xc5, 0x93, 0x98,
	0x98, 0x92, 0x91, 0x58, 0xe4, 0x57, 0x9a, 0x9b, 0x94, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x1c, 0x84, 0x22, 0xa6, 0xa4, 0xcd, 0xc5, 0x1d, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x0a,
	0xd2, 0x22, 0xc3, 0xc5, 0x99, 0x5c, 0x5a, 0x5c, 0xe2, 0x5a, 0x91, 0x59, 0x5c, 0x02, 0x56, 0xcf,
	0x11, 0x84, 0x10, 0x30, 0xea, 0x64, 0xe4, 0x12, 0x73, 0xc6, 0x6a, 0xb3, 0x50, 0x3e, 0x97, 0x12,
	0x76, 0x19, 0xa7, 0xd4, 0xb4, 0xfc, 0xa2, 0x54, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0x54, 0x21, 0x25,
	0x3d, 0x1c, 0xde, 0x42, 0xb8, 0x5a, 0x4a, 0x19, 0xb7, 0x1a, 0xb8, 0x3b, 0x95, 0x18, 0x92, 0xd8,
	0xc0, 0x21, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x34, 0xf7, 0x02, 0xc0, 0x29, 0x01, 0x00,
	0x00,
}
